// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

export function weekKeyISO(date) {
  d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  dayNum = d.getUTCDay();
  if ((dayNum === 0)) {
    dayNum = 7;
  }
  d.setUTCDate(((d.getUTCDate() + 4) - dayNum));
  yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  week = Math.ceil(((((d - yearStart) / 86400000) + 1) / 7));
  return ((d.getUTCFullYear() + "-W") + String(week).padStart(2, "0"));
}
export function startOfWeekISO(date) {
  d = new Date(date);
  day = d.getDay();
  diff = 0;
  if ((day === 0)) {
    diff = ((-6) - day);
  } else {
    diff = (1 - day);
  }
  d.setDate((d.getDate() + diff));
  return d.toISOString().slice(0, 10);
}
export function addDaysISO(iso, n) {
  d = new Date((iso + "T00:00:00Z"));
  d.setUTCDate((d.getUTCDate() + n));
  return d.toISOString().slice(0, 10);
}
