// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

export function haversineKm(a, b) {
  R = 6371;
  dLat = toRad((b.latitude - a.latitude));
  dLon = toRad((b.longitude - a.longitude));
  lat1 = toRad(a.latitude);
  lat2 = toRad(b.latitude);
  x = ((Math.sin((dLat / 2)) * Math.sin((dLat / 2))) + (((Math.sin((dLon / 2)) * Math.sin((dLon / 2))) * Math.cos(lat1)) * Math.cos(lat2)));
  c = (2 * Math.atan2(Math.sqrt(x), Math.sqrt((1 - x))));
  return (R * c);
}
export function toRad(deg) {
  return ((deg * Math.PI) / 180);
}
