// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

import * as Notifications from 'expo-notifications';
export let notificationsModule = null;
export async function requestNotificationPermission() {
  try {
    let permResult = await Notifications.getPermissionsAsync();
    let existingStatus = permResult.status;
    if ((existingStatus === "granted")) {
      return true;
    }
    let reqResult = await Notifications.requestPermissionsAsync();
    return (reqResult.status === "granted");
  } catch (error) {
    return false;
  }
}
export async function scheduleDailyReminder(hour, minute) {
  if ((hour == null)) {
    hour = 20;
  }
  if ((minute == null)) {
    minute = 0;
  }
  try {
    let granted = await requestNotificationPermission();
    if ((!granted)) {
      return null;
    }
    await cancelAllReminders();
    let id = await Notifications.scheduleNotificationAsync({ content: { title: "Nudge", body: "Don't forget to log your activities today! Keep your streak going." }, trigger: { type: "daily", hour: hour, minute: minute } });
    return id;
  } catch (error) {
    return null;
  }
}
export async function cancelAllReminders() {
  try {
    await Notifications.cancelAllScheduledNotificationsAsync();
  } catch (error) {
    console.log("Could not cancel reminders");
  }
}
