// Generated by Quill (Expo mode)
import React, { useState, useEffect, useMemo } from 'react';
import { StyleSheet } from 'react-native';

import 'react-native-gesture-handler';
import * as Nav from '@react-navigation/native';
import * as NativeStack from '@react-navigation/native-stack';
import * as ExpoStatusBar from 'expo-status-bar';
import HomeScreen from './screens/HomeScreen';
import LogActivityScreen from './screens/LogActivityScreen';
import DashboardScreen from './screens/DashboardScreen';
import TipsScreen from './screens/TipsScreen';
import BadgesScreen from './screens/BadgesScreen';
import TrendsScreen from './screens/TrendsScreen';
import SettingsScreen from './screens/SettingsScreen';
import LocationPickerScreen from './screens/LocationPickerScreen';
import OnboardingScreen from './screens/OnboardingScreen';
import ExportScreen from './screens/ExportScreen';
import { AppContext } from './state/context';
import { loadState, saveState, seedIfEmpty } from './state/storage';
import { scheduleDailyReminder } from './lib/notifications';
import { ErrorBoundary } from './ui/ErrorBoundary';
export let screenOptions = { headerStyle: { backgroundColor: "#0b1020" }, headerTintColor: "rgba(255,255,255,0.92)", headerTitleStyle: { fontWeight: "900" } };
export let Stack = NativeStack.createNativeStackNavigator();
export default function App() {
  const [appState, setAppState] = useState(null);
  const [booted, setBooted] = useState(false);

  const api = useMemo(() => ({ booted: booted, state: appState, setState: updateState }), [booted, appState]);

  useEffect(() => {
    async function boot() {
      await seedIfEmpty();
      let s = await loadState();
      setAppState(s);
      setBooted(true);
      try {
        await scheduleDailyReminder(20, 0);
      } catch (error) {
        console.log("reminder setup skipped");
      }
    }
    boot();
  }, []);

  const updateState = async (next) => {
    setAppState(next);
    await saveState(next);
  };

let needsOnboarding = ((booted && appState) && (!appState.onboarded));

  return (
    <ErrorBoundary>
      <AppContext.Provider value={api}>
        <Nav.NavigationContainer>
          <ExpoStatusBar.StatusBar style={"light"} />
          {needsOnboarding ? (
            <Stack.Navigator screenOptions={{ headerShown: false }}>
              <Stack.Screen name={"Onboarding"} component={OnboardingScreen} />
            </Stack.Navigator>
          ) : (
            <Stack.Navigator screenOptions={screenOptions}>
              <Stack.Screen name={"Home"} component={HomeScreen} options={{ title: "Nudge" }} />
              <Stack.Screen name={"LogActivity"} component={LogActivityScreen} options={{ title: "Log Activity" }} />
              <Stack.Screen options={{ title: "Progress Dashboard" }} name={"Dashboard"} component={DashboardScreen} />
              <Stack.Screen name={"Tips"} component={TipsScreen} options={{ title: "Weekly Tips" }} />
              <Stack.Screen options={{ title: "Badges & Streaks" }} name={"Badges"} component={BadgesScreen} />
              <Stack.Screen name={"Trends"} component={TrendsScreen} options={{ title: "Weekly Trends" }} />
              <Stack.Screen name={"Settings"} component={SettingsScreen} options={{ title: "Settings" }} />
              <Stack.Screen options={{ title: "Pick Location" }} name={"PickLocation"} component={LocationPickerScreen} />
              <Stack.Screen name={"Export"} component={ExportScreen} options={{ title: "Export Data" }} />
            </Stack.Navigator>
          )}
        </Nav.NavigationContainer>
      </AppContext.Provider>
    </ErrorBoundary>
  );
}

