// Generated by Quill (Expo mode)
import React, { useState, useEffect, useMemo } from 'react';
import { StyleSheet } from 'react-native';

import 'react-native-gesture-handler';
import * as Nav from '@react-navigation/native';
import * as NativeStack from '@react-navigation/native-stack';
import * as ExpoStatusBar from 'expo-status-bar';
import HomeScreen from './screens/HomeScreen';
import LogActivityScreen from './screens/LogActivityScreen';
import DashboardScreen from './screens/DashboardScreen';
import TipsScreen from './screens/TipsScreen';
import BadgesScreen from './screens/BadgesScreen';
import TrendsScreen from './screens/TrendsScreen';
import SettingsScreen from './screens/SettingsScreen';
import LocationPickerScreen from './screens/LocationPickerScreen';
import OnboardingScreen from './screens/OnboardingScreen';
import ExportScreen from './screens/ExportScreen';
import { AppContext } from './state/context';
import { loadState, saveState, seedIfEmpty } from './state/storage';
import { scheduleDailyReminder } from './lib/notifications';
import { ErrorBoundary } from './ui/ErrorBoundary';
export let screenOptions = { headerStyle: { backgroundColor: "#0b1020" }, headerTintColor: "rgba(255,255,255,0.92)", headerTitleStyle: { fontWeight: "900" } };
export let Stack = NativeStack.createNativeStackNavigator();
export let NavigationContainer = Nav.NavigationContainer;
export let StatusBar = ExpoStatusBar.StatusBar;
export let StackNavigator = Stack["Navigator"];
export let StackScreen = Stack["Screen"];
export let noHeaderOptions = { headerShown: false };
export let optHome = { title: "Nudge" };
export let optLog = { title: "Log Activity" };
export let optDash = { title: "Progress Dashboard" };
export let optTips = { title: "Weekly Tips" };
export let optBadges = { title: "Badges & Streaks" };
export let optTrends = { title: "Weekly Trends" };
export let optSettings = { title: "Settings" };
export let optPickLoc = { title: "Pick Location" };
export let optExport = { title: "Export Data" };
export default function App() {
  const [appState, setAppState] = useState(null);
  const [booted, setBooted] = useState(false);

  const api = useMemo(() => ({ booted: booted, state: appState, setState: updateState }), [booted, appState]);

  useEffect(() => {
    async function boot() {
      await seedIfEmpty();
      let s = await loadState();
      setAppState(s);
      setBooted(true);
      try {
        await scheduleDailyReminder(20, 0);
      } catch (error) {
        console.log("reminder setup skipped");
      }
    }
    boot();
  }, []);

  const updateState = async (next) => {
    setAppState(next);
    await saveState(next);
  };

let needsOnboarding = ((booted && appState) && (!appState.onboarded));

  return (
    <ErrorBoundary>
      <AppContext.Provider value={api}>
        <NavigationContainer>
          <StatusBar style={"light"} />
          {needsOnboarding ? (
            <StackNavigator screenOptions={noHeaderOptions}>
              <StackScreen name={"Onboarding"} component={OnboardingScreen} />
            </StackNavigator>
          ) : (
            <StackNavigator screenOptions={screenOptions}>
              <StackScreen name={"Home"} component={HomeScreen} options={optHome} />
              <StackScreen options={optLog} name={"LogActivity"} component={LogActivityScreen} />
              <StackScreen name={"Dashboard"} component={DashboardScreen} options={optDash} />
              <StackScreen name={"Tips"} component={TipsScreen} options={optTips} />
              <StackScreen name={"Badges"} component={BadgesScreen} options={optBadges} />
              <StackScreen name={"Trends"} component={TrendsScreen} options={optTrends} />
              <StackScreen name={"Settings"} component={SettingsScreen} options={optSettings} />
              <StackScreen name={"PickLocation"} component={LocationPickerScreen} options={optPickLoc} />
              <StackScreen options={optExport} name={"Export"} component={ExportScreen} />
            </StackNavigator>
          )}
        </NavigationContainer>
      </AppContext.Provider>
    </ErrorBoundary>
  );
}

