// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

import AsyncStorage from '@react-native-async-storage/async-storage';
export let KEY = "scfd_state_v2";
export let OLD_KEY = "scfd_state_v1";
export function defaultState() {
  return { school: null, home: null, targetKgPerWeek: 10, region: "world", onboarded: false, logs: [] };
}
export function migrateV1(v1) {
  let logs = (v1.logs || []).map((l) => Object.assign({}, l, { category: "transport", itemKey: (l.transport || "car"), label: ((l.transportLabel || l.transport) || "Car"), quantity: 1 }));
  return Object.assign({}, defaultState(), { school: (v1.school || null), home: (v1.home || null), targetKgPerWeek: (v1.targetKgPerWeek || 10), onboarded: true, logs: logs });
}
export async function readStore(key) {
  try {
    let raw = await AsyncStorage.getItem(key);
    if ((!raw)) {
      return null;
    }
    return JSON.parse(raw);
  } catch (error) {
    console.log(`readStore failed: ${error}`);
    return null;
  }
}
export async function writeStore(key, value) {
  await AsyncStorage.setItem(key, JSON.stringify(value));
}
export async function seedIfEmpty() {
  try {
    let existing = await readStore(KEY);
    if (existing) {
      return null;
    }
    let v1Raw = await readStore(OLD_KEY);
    if (v1Raw) {
      let migrated = migrateV1(v1Raw);
      await writeStore(KEY, migrated);
      return null;
    }
    await writeStore(KEY, defaultState());
  } catch (error) {
    console.log(`seedIfEmpty failed, using defaults: ${error}`);
  }
}
export async function loadState() {
  try {
    let raw = await readStore(KEY);
    if ((!raw)) {
      return defaultState();
    }
    return Object.assign({}, defaultState(), raw);
  } catch (error) {
    console.log(`loadState failed, using defaults: ${error}`);
    return defaultState();
  }
}
export async function saveState(appData) {
  try {
    await writeStore(KEY, appData);
  } catch (error) {
    console.log(`saveState failed: ${error}`);
    throw new Error("Could not save your data. Please try again.");
  }
}
