// Generated by Quill (Expo mode)
import React, { useMemo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

import { bg, card, border, textColor, muted, brand } from './theme';
export function Screen({ children, extraStyle }) {
  return (
    <View style={styles.screenBase}>
      {children}
    </View>
  );
}

export function Card({ children, extraStyle }) {
  return (
    <View style={styles.cardBase} accessibilityRole={"summary"}>
      {children}
    </View>
  );
}

export function Title({ children, extraStyle }) {
  return (
    <Text style={styles.titleBase} accessibilityRole={"header"}>
      {children}
    </Text>
  );
}

export function Muted({ children, extraStyle }) {
  return (
    <Text style={styles.mutedBase}>
      {children}
    </Text>
  );
}

export function Button({ label, onPress, kind, disabled, accessibilityLabel }) {
  const accessLabel = () => {
    return (accessibilityLabel || label);
  };

let al = accessLabel();

  return (
    <Pressable disabled={disabled} onPress={() => onPress()} accessibilityRole={"button"} accessibilityLabel={al}>
      {(kind === "ghost") ? (
        <Text style={styles.btnGhostText}>{label}</Text>
      ) : (
        <Text style={styles.btnPrimaryText}>{label}</Text>
      )}
    </Pressable>
  );
}

export function Chip({ label, kind }) {
  return (
    <>
      {(kind === "brand") ? (
        <View style={styles.chipBrandView} accessibilityLabel={label}>
          <Text style={styles.chipBrandText}>{label}</Text>
        </View>
      ) : (
        <View style={styles.chipView} accessibilityLabel={label}>
          <Text style={styles.chipTextNormal}>{label}</Text>
        </View>
      )}
    </>
  );
}

export default function ProgressRing({ progress, size, strokeWidth, color, bgColor, children }) {
  const p = useMemo(() => Math.max(0, Math.min(1, (progress || 0))), [progress]);
  const sz = useMemo(() => (size || 120), [size]);
  const sw = useMemo(() => (strokeWidth || 10), [strokeWidth]);
  const clr = useMemo(() => (color || brand), [color]);
  const bgc = useMemo(() => (bgColor || "rgba(255,255,255,0.08)"), [bgColor]);
  const pct = useMemo(() => Math.round((p * 100)), [p]);
  const isOver50 = useMemo(() => (pct > 50), [pct]);
  const rotation = useMemo(() => (p * 360), [p]);

  return (
    <View style={{ width: sz, height: sz, alignItems: "center", justifyContent: "center" }} accessibilityLabel={`Progress: ${pct}%`} accessibilityRole={"progressbar"}>
      <View style={{ position: "absolute", width: sz, height: sz, borderRadius: (sz / 2), borderWidth: sw, borderColor: bgc }} />
      <View style={{ position: "absolute", width: sz, height: sz, overflow: "hidden" }}>
        <View style={{ position: "absolute", width: (sz / 2), height: sz, right: 0, overflow: "hidden" }}>
          <View style={{ width: sz, height: sz, borderRadius: (sz / 2), borderWidth: sw, borderColor: clr, borderLeftColor: "transparent", borderBottomColor: "transparent", transform: [{ rotate: (Math.min(rotation, 180) + "deg") }] }} />
        </View>
      </View>
      {isOver50 && (
        <View style={{ position: "absolute", width: sz, height: sz, overflow: "hidden" }}>
          <View style={{ position: "absolute", width: (sz / 2), height: sz, left: 0, overflow: "hidden" }}>
            <View style={{ width: sz, height: sz, borderRadius: (sz / 2), borderWidth: sw, borderColor: clr, borderRightColor: "transparent", borderTopColor: "transparent", transform: [{ rotate: ((rotation - 180) + "deg") }] }} />
          </View>
        </View>
      )}
      <View style={{ alignItems: "center", justifyContent: "center" }}>
        {children}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  chipTextNormal: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    fontSize: 12,
  },
  chipBrandText: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "900",
    fontSize: 12,
  },
  cardBase: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
  },
  titleBase: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 22,
    fontWeight: "900",
  },
  btnPrimaryText: {
    color: "#081019",
    fontWeight: "900",
  },
  btnGhostText: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "900",
  },
  chipBrandView: {
    borderWidth: 1,
    borderColor: "rgba(45,212,191,0.55)",
    backgroundColor: "rgba(45,212,191,0.15)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  chipView: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.03)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    alignSelf: "flex-start",
  },
  screenBase: {
    flex: 1,
    backgroundColor: "#0b1020",
    padding: 16,
  },
  mutedBase: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 13,
    lineHeight: 18,
  },
});
