// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

import { ErrorBoundary as RawErrorBoundary } from 'react-error-boundary';
export function errorFallback(props) {
  return React.createElement(View, { style: { flex: 1, backgroundColor: "#0b1020", alignItems: "center", justifyContent: "center", padding: 32 } }, React.createElement(Text, { style: { fontSize: 48, color: "#ef4444", fontWeight: "900", marginBottom: 16 } }, "!"), React.createElement(Text, { style: { color: "rgba(255,255,255,0.92)", fontSize: 22, fontWeight: "900", marginBottom: 8 } }, "Something went wrong"), React.createElement(Text, { style: { color: "rgba(255,255,255,0.68)", fontSize: 14, textAlign: "center", lineHeight: 20 } }, ((props.error && props.error.message) || "An unexpected error occurred.")), React.createElement(Pressable, { onPress: props.resetErrorBoundary, style: { marginTop: 24, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 12, backgroundColor: "#2dd4bf", alignItems: "center" } }, React.createElement(Text, { style: { color: "#081019", fontWeight: "900" } }, "Try Again")));
}
export function ErrorBoundary(props) {
  return React.createElement(RawErrorBoundary, { FallbackComponent: errorFallback }, props.children);
}
