// Generated by Quill (Expo mode)
import React from 'react';
import { StyleSheet } from 'react-native';

export let bg = "#0b1020";
export let card = "rgba(255,255,255,0.06)";
export let border = "rgba(255,255,255,0.12)";
export let textColor = "rgba(255,255,255,0.92)";
export let muted = "rgba(255,255,255,0.68)";
export let brand = "#2dd4bf";
export let brand2 = "#7c5cff";
export let danger = "#ef4444";
