// Generated by Quill (Expo mode)
import React, { useContext, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Chip } from '../ui/components';
import { brand, textColor, muted, border } from '../ui/theme';
import { computeWeeklyScore } from '../lib/co2';
import { weekKeyISO } from '../utils/time';
import { BADGES, computeStats, computeStreak, getEarnedBadges, getNextBadge } from '../lib/badges';
export default function BadgesScreen() {
  const ctx = useContext(AppContext);
  const result = useMemo(() => computeBadgeData(ctx.state), [ctx]);

  const computeBadgeData = (appData) => {
    let logs = (__propagate(appData).logs || []);
    let now = new Date();
    let thisWk = weekKeyISO(now);
    let prevDate = new Date(now);
    prevDate.setDate((prevDate.getDate() - 7));
    let prevWk = weekKeyISO(prevDate);
    function weekScore(wk) {
      let wLogs = logs.filter((l) => (weekKeyISO(new Date(l.dateISO)) === wk));
      let daily = {};
      for (const l of wLogs) {
        let day = new Date(l.dateISO).toISOString().slice(0, 10);
        daily[day] = ((daily[day] || 0) + (l.co2Kg || 0));
      }
      return computeWeeklyScore(Object.values(daily));
    }
    let thisScore = weekScore(thisWk);
    let prevScore = weekScore(prevWk);
    let s = computeStats(logs, thisScore, prevScore);
    let e = getEarnedBadges(s);
    let n = getNextBadge(s);
    let streak = computeStreak(logs);
    return { earned: e, nextBadge: n, streakInfo: streak, stats: s };
  };

  const streakUnitLabel = (count) => {
    if ((count !== 1)) {
      return "days";
    } else {
      return "day";
    }
  };

  return (
    <Screen>
      <ScrollView>
        <Card>
          <View style={styles.streakRow}>
            <View style={styles.streakCircle} accessibilityLabel={`Current streak: ${result.streakInfo.currentStreak} days`} accessibilityRole={"text"}>
              <Text style={styles.streakNumber}>{result.streakInfo.currentStreak}</Text>
              <Text style={styles.streakUnit}>{streakUnitLabel(result.streakInfo.currentStreak)}</Text>
            </View>
            <View style={styles.streakMeta}>
              <Title>Current Streak</Title>
              <Muted style={styles.streakMetaDetail}>Longest streak: {result.streakInfo.longestStreak} days</Muted>
              <Muted>Total activities logged: {result.stats.totalLogs}</Muted>
            </View>
          </View>
          {(result.streakInfo.currentStreak > 0) && (
            <View style={styles.graceNote} accessibilityRole={"alert"}>
              <Muted style={styles.graceNoteText}>Streaks include a 1-day grace period — if you miss today, you have until tomorrow to log and keep your streak alive.</Muted>
            </View>
          )}
        </Card>
        <View style={styles.spacer12} />
        <Card>
          <Title style={styles.sectionTitle18}>Badges Earned ({result.earned.length}/{BADGES.length})</Title>
          <Muted style={styles.spacerTop4}>Complete challenges to unlock badges</Muted>
          <View style={styles.spacer12} />
          {(result.earned.length > 0) ? (
            <View style={styles.badgeGrid}>
              {result.earned.map((b, __idx) => (
                <View style={styles.badgeCard}>
                  <Text style={styles.badgeIcon}>{b.icon}</Text>
                  <Text style={styles.badgeName}>{b.name}</Text>
                  <Text style={styles.badgeDesc}>{b.desc}</Text>
                </View>
              ))}
            </View>
          ) : (
            <Muted>No badges yet. Start logging activities to earn them!</Muted>
          )}
        </Card>
        <View style={styles.spacer12} />
        {result.nextBadge && (
          <Card style={styles.nextBadgeCard}>
            <Title style={styles.sectionTitle16}>Next Badge</Title>
            <View style={styles.nextBadgeRow}>
              <Text style={styles.nextBadgeIcon}>{result.nextBadge.icon}</Text>
              <View style={styles.nextBadgeMeta}>
                <Text style={styles.nextBadgeName}>{result.nextBadge.name}</Text>
                <Text style={styles.nextBadgeDesc}>{result.nextBadge.desc}</Text>
              </View>
            </View>
          </Card>
        )}
        <View style={styles.spacer12} />
        <Card>
          <Title style={styles.sectionTitle16}>All Badges</Title>
          <View style={styles.spacerTop10}>
            {BADGES.map((b, __idx) => (
              {result.earned.some((e) => (e.id === b.id)) ? (
                <View style={styles.allBadgeRow}>
                  <Text style={styles.allBadgeIcon}>{b.icon}</Text>
                  <View style={styles.flex1}>
                    <Text style={styles.allBadgeName}>{b.name}</Text>
                    <Text style={styles.allBadgeDesc}>{b.desc}</Text>
                  </View>
                  <Chip label={"Earned"} kind={"brand"} />
                </View>
              ) : (
                <View style={[styles.allBadgeRow, styles.dimmed]}>
                  <Text style={styles.allBadgeIcon}>{b.icon}</Text>
                  <View style={styles.flex1}>
                    <Text style={styles.allBadgeName}>{b.name}</Text>
                    <Text style={styles.allBadgeDesc}>{b.desc}</Text>
                  </View>
                </View>
              )}
            ))}
          </View>
        </Card>
        <View style={styles.spacer30} />
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  nextBadgeMeta: {
    flex: 1,
    marginLeft: 12,
  },
  badgeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  spacerTop4: {
    marginTop: 4,
  },
  spacerTop10: {
    marginTop: 10,
  },
  flex1: {
    flex: 1,
  },
  streakMeta: {
    flex: 1,
    marginLeft: 16,
  },
  nextBadgeIcon: {
    fontSize: 40,
  },
  nextBadgeCard: {
    borderWidth: 1,
    borderColor: "rgba(45,212,191,0.3)",
  },
  nextBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  allBadgeIcon: {
    fontSize: 24,
    width: 36,
  },
  allBadgeDesc: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
  },
  nextBadgeName: {
    color: "#2dd4bf",
    fontWeight: "900",
    fontSize: 16,
  },
  spacer30: {
    height: 30,
  },
  badgeDesc: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 11,
    textAlign: "center",
    marginTop: 2,
  },
  sectionTitle16: {
    fontSize: 16,
  },
  streakMetaDetail: {
    marginTop: 4,
  },
  graceNote: {
    backgroundColor: "rgba(245,158,11,0.08)",
    borderRadius: 10,
    padding: 10,
    marginTop: 12,
  },
  spacer12: {
    height: 12,
  },
  streakNumber: {
    color: "#f59e0b",
    fontSize: 28,
    fontWeight: "900",
  },
  graceNoteText: {
    fontSize: 12,
    textAlign: "center",
  },
  badgeIcon: {
    fontSize: 36,
    marginBottom: 6,
  },
  dimmed: {
    opacity: 0.4,
  },
  badgeCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    width: "47%",
  },
  streakRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  streakUnit: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontWeight: "700",
  },
  nextBadgeDesc: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 13,
    marginTop: 2,
  },
  sectionTitle18: {
    fontSize: 18,
  },
  allBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
    gap: 8,
  },
  streakCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#f59e0b",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(245,158,11,0.08)",
  },
  badgeName: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "900",
    fontSize: 13,
    textAlign: "center",
  },
  allBadgeName: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "900",
    fontSize: 14,
  },
});
