// Generated by Quill (Expo mode)
import React, { useContext, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Chip, ProgressRing } from '../ui/components';
import { brand, brand2, textColor, muted } from '../ui/theme';
import { CATEGORIES, computeDailyScore, computeWeeklyScore, compareToBenchmark } from '../lib/co2';
import { weekKeyISO, startOfWeekISO, addDaysISO } from '../utils/time';
export function clamp(n, a, b) {
  return Math.max(a, Math.min(b, n));
}
export default function DashboardScreen() {
  const ctx = useContext(AppContext);

  const data = useMemo(() => computeData(ctx.state), [ctx]);

  const computeData = (appData) => {
    let logs = (__propagate(appData).logs || []);
    let now = new Date();
    let weeks = [];
    let w = 0;
    while ((w < 4)) {
      let d = new Date(now);
      d.setDate((d.getDate() - (w * 7)));
      let wk = weekKeyISO(d);
      let startISO = startOfWeekISO(d);
      let weekLogs = logs.filter((l) => (weekKeyISO(new Date(l.dateISO)) === wk));
      let totalKg = weekLogs.reduce((a, l) => (a + (l.co2Kg || 0)), 0);
      let catTotals = { transport: 0, diet: 0, energy: 0, waste: 0 };
      for (const l of weekLogs) {
        let cat = (l.category || "transport");
        catTotals[cat] = ((catTotals[cat] || 0) + (l.co2Kg || 0));
      }
      let daily = {};
      for (const l of weekLogs) {
        let day = new Date(l.dateISO).toISOString().slice(0, 10);
        daily[day] = ((daily[day] || 0) + (l.co2Kg || 0));
      }
      let weeklyScore = computeWeeklyScore(Object.values(daily));
      weeks.push({ wk: wk, startISO: startISO, totalKg: totalKg, catTotals: catTotals, weeklyScore: weeklyScore, logCount: weekLogs.length });
      w = (w + 1);
    }
    let currentWk = weekKeyISO(now);
    let currentStart = startOfWeekISO(now);
    let dailyBreakdown = Array.from({ length: 7 }).map((_, i) => {
      let dayISO = addDaysISO(currentStart, i);
      let dayLogs = logs.filter((l) => ((weekKeyISO(new Date(l.dateISO)) === currentWk) && (new Date(l.dateISO).toISOString().slice(0, 10) === dayISO)));
      let kg = dayLogs.reduce((a, l) => (a + (l.co2Kg || 0)), 0);
      return { dayISO: dayISO, kg: kg, score: computeDailyScore(kg) };
    });
    let region = (__propagate(appData).region || "world");
    let target = (__propagate(appData).targetKgPerWeek || 10);
    let benchmark = compareToBenchmark((__propagate(weeks[0]).totalKg || 0), region);
    return { weeks: weeks, dailyBreakdown: dailyBreakdown, benchmark: benchmark, target: target };
  };

  const pickScoreColor = (score) => {
    if ((!(score < 70))) {
      return "#22c55e";
    }
    if ((!(score < 40))) {
      return "#f59e0b";
    }
    return "#ef4444";
  };

  const pickImprovementKind = (improvement) => {
    if ((Number(improvement) > 0)) {
      return "brand";
    }
    return "default";
  };

  const pickImprovementLabel = (improvement) => {
    if ((Number(improvement) > 0)) {
      return `${improvement}% better than last week`;
    }
    return `${Math.abs(improvement)}% more than last week`;
  };

  const pickGoalColor = (currentKg, targetKg) => {
    if ((currentKg > targetKg)) {
      return "#ef4444";
    }
    return brand;
  };

  const pickBenchmarkColor = (isBetter) => {
    if (isBetter) {
      return "#22c55e";
    }
    return "#ef4444";
  };

  const pickDayLabelStyle = (isToday) => {
    if (isToday) {
      return [dayLabelStyle, { color: brand }];
    }
    return [dayLabelStyle, null];
  };

  const pickDayLabelText = (dayLabel, isToday) => {
    if (isToday) {
      return `${dayLabel} (today)`;
    }
    return dayLabel;
  };

  const pickDayKgText = (kg) => {
    if ((kg > 0)) {
      return (kg.toFixed(2) + " kg");
    }
    return "—";
  };

  const pickDayScoreText = (kg, score) => {
    if ((kg > 0)) {
      return `${score}`;
    }
    return "—";
  };

  const pickTrendLabelStyle = (idx) => {
    if ((idx === 3)) {
      return [dayLabelStyle, { color: brand }];
    }
    return [dayLabelStyle, null];
  };

  const pickTrendLabelText = (startISO, idx) => {
    if ((idx === 3)) {
      return `${startISO} (current)`;
    }
    return startISO;
  };

  const pickTrendBarColor = (idx) => {
    if ((idx === 3)) {
      return brand;
    }
    return "rgba(255,255,255,0.2)";
  };

  const catBarFillStyle = (pct, catColor) => {
    return [barFill, { width: (clamp(pct, 0, 100) + "%"), backgroundColor: catColor }];
  };

  const dayScoreStyle = (score) => {
    return [dayScoreText, { color: pickScoreColor(score) }];
  };

  const dailyBarFillStyle = (pct) => {
    return [barFill, { width: (clamp(pct, 0, 100) + "%"), backgroundColor: brand2 }];
  };

  const trendBarFillStyle = (pct, idx) => {
    return [barFill, { width: (clamp(pct, 0, 100) + "%"), backgroundColor: pickTrendBarColor(idx) }];
  };

let thisWeek = data.weeks[0];
let lastWeek = data.weeks[1];
let weeklyKgValues = data.weeks.map((w) => w.totalKg);
let maxWeeklyKg = Math.max.apply(Math, [1].concat(weeklyKgValues));
let dailyKgValues = data.dailyBreakdown.map((d) => d.kg);
let maxDailyKg = Math.max.apply(Math, [1].concat(dailyKgValues));
let improvement = null;

  return (
    <>
      {(__propagate(lastWeek).totalKg > 0) && (
        const improvement = (((lastWeek.totalKg - thisWeek.totalKg) / lastWeek.totalKg) * 100).toFixed(0);
      )}
      <Screen>
        <ScrollView showsVerticalScrollIndicator={false}>
          <Card>
            <View style={styles.scoreRow}>
              <View style={styles.scoreCircle}>
                <Text style={styles.scoreNumber}>{thisWeek.weeklyScore}</Text>
                <Text style={styles.scoreLabel}>Score</Text>
              </View>
              <View style={{ flex: 1, marginLeft: 16 }}>
                <Title>This Week</Title>
                <Muted style={{ marginTop: 4 }}>{thisWeek.totalKg.toFixed(1)} kg CO2e from {thisWeek.logCount} activities</Muted>
                {(improvement != null) && (
                  <>
                    const chipKind = pickImprovementKind(improvement);
                    const chipLabel = pickImprovementLabel(improvement);
                    <View style={{ marginTop: 6 }}>
                      <Chip kind={chipKind} label={chipLabel} />
                    </View>
                  </>
                )}
              </View>
            </View>
          </Card>
          <View style={{ height: 12 }} />
          <Card>
            <Title style={{ fontSize: 18 }}>Goal & Benchmark</Title>
            const ringProgress = Math.min((thisWeek.totalKg / data.target), 1);
            const ringColor = pickGoalColor(thisWeek.totalKg, data.target);
            const ringPct = Math.round(Math.min(((thisWeek.totalKg / data.target) * 100), 999));
            <View style={{ flexDirection: "row", alignItems: "center", marginTop: 12, gap: 16 }}>
              <ProgressRing progress={ringProgress} size={100} strokeWidth={10} color={ringColor}>
                <Text style={{ color: textColor, fontSize: 18, fontWeight: "900" }}>{ringPct}%</Text>
              </ProgressRing>
              const benchColor = pickBenchmarkColor(data.benchmark.better);
              <View style={{ flex: 1 }}>
                <Text style={{ color: textColor, fontWeight: "700", fontSize: 14 }}>{thisWeek.totalKg.toFixed(1)} / {data.target} kg goal</Text>
                <View style={{ height: 6 }} />
                {data.benchmark.better ? (
                  <Text style={{ color: benchColor, fontWeight: "700", fontSize: 13 }}>{data.benchmark.savedPct.toFixed(0)}% below {data.benchmark.benchmarkLabel}</Text>
                ) : (
                  <Text style={{ color: benchColor, fontWeight: "700", fontSize: 13 }}>{Math.abs(data.benchmark.savedPct).toFixed(0)}% above {data.benchmark.benchmarkLabel}</Text>
                )}
                <Muted style={{ fontSize: 11, marginTop: 2 }}>National avg: {data.benchmark.benchmarkKg} kg/week</Muted>
                <Muted style={{ fontSize: 9, marginTop: 2 }}>Source: {data.benchmark.benchmarkSource}</Muted>
              </View>
            </View>
          </Card>
          <View style={{ height: 12 }} />
          <Card>
            <Title style={{ fontSize: 18 }}>Category Breakdown</Title>
            <Muted style={{ marginTop: 4 }}>This week's CO2e by domain</Muted>
            <View style={{ marginTop: 12 }}>
              {Object.entries(CATEGORIES).map((entry, __idx) => (
                <>
                  const key = entry[0];
                  const cat = entry[1];
                  const kg = (thisWeek.catTotals[key] || 0);
                  const totalKg = Math.max(0.01, thisWeek.totalKg);
                  const pct = ((kg / totalKg) * 100);
                  const catStyle = catBarFillStyle(pct, cat.color);
                  <View style={{ marginBottom: 12 }}>
                    <View style={styles.catHeader}>
                      <Text style={styles.catName}>{cat.icon} {cat.label}</Text>
                      <Text style={styles.catKg}>{kg.toFixed(2)} kg</Text>
                    </View>
                    <View style={styles.barBg}>
                      <View style={catStyle} />
                    </View>
                  </View>
                </>
              ))}
            </View>
          </Card>
          <View style={{ height: 12 }} />
          <Card>
            <Title style={{ fontSize: 18 }}>Daily Emissions</Title>
            <Muted style={{ marginTop: 4 }}>CO2e per day this week</Muted>
            <View style={{ marginTop: 12 }}>
              {data.dailyBreakdown.map((d, __idx) => (
                <>
                  const pct = ((d.kg / maxDailyKg) * 100);
                  const dayLabel = new Date((d.dayISO + "T00:00:00Z")).toLocaleDateString(null, { weekday: "short" });
                  const isToday = (d.dayISO === new Date().toISOString().slice(0, 10));
                  const dlStyle = pickDayLabelStyle(isToday);
                  const dlText = pickDayLabelText(dayLabel, isToday);
                  const dkText = pickDayKgText(d.kg);
                  const dsStyle = dayScoreStyle(d.score);
                  const dsText = pickDayScoreText(d.kg, d.score);
                  const dbStyle = dailyBarFillStyle(pct);
                  <View style={{ marginBottom: 8 }}>
                    <View style={styles.dayRow}>
                      <Text style={dlStyle}>{dlText}</Text>
                      <Text style={styles.dayKg}>{dkText}</Text>
                      <View style={styles.dayScoreBadge}>
                        <Text style={dsStyle}>{dsText}</Text>
                      </View>
                    </View>
                    <View style={styles.barBg}>
                      <View style={dbStyle} />
                    </View>
                  </View>
                </>
              ))}
            </View>
          </Card>
          <View style={{ height: 12 }} />
          <Card>
            <Title style={{ fontSize: 18 }}>4-Week Trend</Title>
            <Muted style={{ marginTop: 4 }}>Total CO2e over recent weeks</Muted>
            <View style={{ marginTop: 12 }}>
              const reversed = data.weeks.slice().reverse();
              {reversed.map((w, __idx) => (
                <>
                  const i = reversed.indexOf(w);
                  const pct = ((w.totalKg / maxWeeklyKg) * 100);
                  const tlStyle = pickTrendLabelStyle(i);
                  const tlText = pickTrendLabelText(w.startISO, i);
                  const tbStyle = trendBarFillStyle(pct, i);
                  <View style={{ marginBottom: 10 }}>
                    <View style={styles.dayRow}>
                      <Text style={tlStyle}>{tlText}</Text>
                      <Text style={styles.dayKg}>{w.totalKg.toFixed(1)} kg</Text>
                    </View>
                    <View style={styles.barBg}>
                      <View style={tbStyle} />
                    </View>
                  </View>
                </>
              ))}
            </View>
          </Card>
          <View style={{ height: 30 }} />
        </ScrollView>
      </Screen>
    </>
  );
}

const styles = StyleSheet.create({
  catHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  catKg: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    fontSize: 13,
  },
  barFill: {
    height: "100%",
    borderRadius: 999,
  },
  scoreLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontWeight: "700",
  },
  dayRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  dayScoreBadge: {
    width: 30,
    alignItems: "flex-end",
  },
  scoreRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  scoreNumber: {
    color: "#2dd4bf",
    fontSize: 28,
    fontWeight: "900",
  },
  dayLabelStyle: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "700",
    fontSize: 13,
    flex: 1,
  },
  dayKg: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    fontSize: 12,
    marginRight: 8,
  },
  scoreCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "#2dd4bf",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(45,212,191,0.08)",
  },
  catName: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "700",
    fontSize: 14,
  },
  barBg: {
    height: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  dayScoreText: {
    fontWeight: "900",
    fontSize: 13,
  },
});
