// Generated by Quill (Expo mode)
import React, { useState, useContext, useMemo } from 'react';
import { Alert, ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Button } from '../ui/components';
import { brand, textColor, muted } from '../ui/theme';
export function escapeCSV(val) {
  let str = String((val || ""));
  let quote = String.fromCharCode(34);
  let nl = String.fromCharCode(10);
  let quotePattern = new RegExp(String.fromCharCode(34), "g");
  if (((str.includes(",") || str.includes(quote)) || str.includes(nl))) {
    return ((quote + str.replace(quotePattern, (quote + quote))) + quote);
  }
  return str;
}
export function logsToCSV(logs) {
  let headers = ["Date", "Category", "Activity", "CO2 (kg)", "Quantity", "Notes"];
  let rows = logs.map((l) => [(l.dateISO?.slice(0, 10) || ""), (l.category || "transport"), ((l.label || l.itemKey) || ""), (l.co2Kg || 0).toFixed(3), (l.quantity || 1), (l.notes || "")]);
  let csvLines = [headers].concat(rows).map((row) => row.map(escapeCSV).join(","));
  return csvLines.join(String.fromCharCode(10));
}
export default function ExportScreen() {
  const ctx = useContext(AppContext);
  const [shared, setShared] = useState(false);

  const deriveLogs = (appData) => {
    return (appData?.logs || []);
  };

  const deriveCSV = (logList) => {
    return logsToCSV(logList);
  };

  const deriveStats = (logList) => {
    let total = logList.reduce((a, l) => (a + (l.co2Kg || 0)), 0);
    let dates = new Set(logList.map((l) => l.dateISO?.slice(0, 10)));
    return { count: logList.length, totalKg: total, days: dates.size };
  };

  const deriveIsEmpty = (logList) => {
    return (logList.length === 0);
  };

  const onShare = async () => {
    try {
      const RN = require("react-native");
      let currentLogs = (ctx.state?.logs || []);
      let currentCsv = logsToCSV(currentLogs);
      await RN.Share.share({ message: currentCsv, title: "Nudge - Carbon Footprint Data" });
      setShared(true);
    } catch (error) {
      Alert.alert("Export", (error?.message || "Could not share data"));
    }
  };

  const logs = useMemo(() => deriveLogs(ctx.state), [ctx]);
  const csv = useMemo(() => deriveCSV(logs), [logs]);
  const stats = useMemo(() => deriveStats(logs), [logs]);
  const isEmpty = useMemo(() => deriveIsEmpty(logs), [logs]);

  return (
    <Screen>
      <ScrollView showsVerticalScrollIndicator={false}>
        <Card>
          <Title>Export Your Data</Title>
          <Muted style={styles.hintStyle}>Share your carbon footprint logs as CSV. You can paste this into Google Sheets, Excel, or use it in your EPQ analysis.</Muted>
          <View style={styles.statsRow}>
            <View style={styles.statBox} accessibilityLabel={`Activities: ${stats.count}`}>
              <Text style={styles.statValue}>{stats.count}</Text>
              <Text style={styles.statLabel}>Activities</Text>
            </View>
            <View style={styles.statBox} accessibilityLabel={`Days: ${stats.days}`}>
              <Text style={styles.statValue}>{stats.days}</Text>
              <Text style={styles.statLabel}>Days</Text>
            </View>
            <View style={styles.statBox} accessibilityLabel={`Total kg: ${stats.totalKg.toFixed(1)}`}>
              <Text style={styles.statValue}>{stats.totalKg.toFixed(1)}</Text>
              <Text style={styles.statLabel}>Total kg</Text>
            </View>
          </View>
        </Card>
        <View style={styles.spacerSmall} />
        <Card>
          <Title style={styles.previewTitle}>CSV Preview</Title>
          <View style={styles.previewBox}>
            <Text style={styles.previewText}>{csv || 'No data to export yet.'}</Text>
          </View>
        </Card>
        <View style={styles.spacerSmall} />
        <Card>
          <Button label={"Share CSV"} onPress={onShare} disabled={isEmpty} />
          {shared && (
            <Muted style={styles.successHint}>Data shared successfully!</Muted>
          )}
          {isEmpty && (
            <Muted style={styles.successHint}>Log some activities first to export data.</Muted>
          )}
        </Card>
        <View style={styles.spacerLarge} />
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  spacerSmall: {
    height: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
  },
  statLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  previewTitle: {
    fontSize: 16,
  },
  previewBox: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 8,
    padding: 10,
    marginTop: 8,
  },
  spacerLarge: {
    height: 30,
  },
  successHint: {
    marginTop: 8,
    textAlign: "center",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  statValue: {
    color: "#2dd4bf",
    fontSize: 22,
    fontWeight: "900",
  },
  previewText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontFamily: "monospace",
    lineHeight: 14,
  },
  hintStyle: {
    marginTop: 6,
  },
});
