// Generated by Quill (Expo mode)
import React, { useContext, useMemo } from 'react';
import { FlatList, StyleSheet, Text, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Button, Chip, ProgressRing } from '../ui/components';
import { brand, textColor, muted } from '../ui/theme';
import { CATEGORIES, computeDailyScore, computeWeeklyScore, compareToBenchmark, WEEKLY_BENCHMARKS } from '../lib/co2';
import { weekKeyISO, startOfWeekISO } from '../utils/time';
import { computeStreak } from '../lib/badges';
export function sortByDateDesc(a, b) {
  if ((b.dateISO > a.dateISO)) {
    return 1;
  }
  if ((b.dateISO < a.dateISO)) {
    return (-1);
  }
  return 0;
}
export function pickGoalColor(over) {
  if ((over > 0)) {
    return "#ef4444";
  }
  return brand;
}
export function pickBenchmarkBg(better) {
  if (better) {
    return "rgba(34,197,94,0.12)";
  }
  return "rgba(239,68,68,0.12)";
}
export function pickBenchmarkBorder(better) {
  if (better) {
    return "rgba(34,197,94,0.3)";
  }
  return "rgba(239,68,68,0.3)";
}
export function pickBenchmarkTextColor(better) {
  if (better) {
    return "#22c55e";
  }
  return "#ef4444";
}
export function pickLogColor(co2Val) {
  if ((co2Val < 0)) {
    return "#22c55e";
  }
  return textColor;
}
export function pickLogPrefix(co2Val) {
  if ((!(co2Val < 0))) {
    return "+";
  }
  return "";
}
export default function HomeScreen({ navigation }) {
  const ctx = useContext(AppContext);

  const goLogActivity = () => {
    navigation.navigate("LogActivity");
  };

  const goDashboard = () => {
    navigation.navigate("Dashboard");
  };

  const goTips = () => {
    navigation.navigate("Tips");
  };

  const goBadges = () => {
    navigation.navigate("Badges");
  };

  const goSettings = () => {
    navigation.navigate("Settings");
  };

  const goExport = () => {
    navigation.navigate("Export");
  };

  const computeSummary = (appData) => {
    let logs = (appData?.logs || []);
    let now = new Date();
    let wk = weekKeyISO(now);
    let today = now.toISOString().slice(0, 10);
    let weekLogs = logs.filter((l) => (weekKeyISO(new Date(l.dateISO)) === wk));
    let totalKg = weekLogs.reduce((a, l) => (a + (l.co2Kg || 0)), 0);
    let target = (appData?.targetKgPerWeek || 10);
    let catTotals = { transport: 0, diet: 0, energy: 0, waste: 0 };
    for (const l of weekLogs) {
      catTotals[(l.category || "transport")] = (catTotals[(l.category || "transport")] + (l.co2Kg || 0));
    }
    let todayLogs = logs.filter((l) => (new Date(l.dateISO).toISOString().slice(0, 10) === today));
    let todayKg = todayLogs.reduce((a, l) => (a + (l.co2Kg || 0)), 0);
    let todayScore = computeDailyScore(todayKg);
    let daily = {};
    for (const l of weekLogs) {
      let day = new Date(l.dateISO).toISOString().slice(0, 10);
      daily[day] = ((daily[day] || 0) + (l.co2Kg || 0));
    }
    let weeklyScore = computeWeeklyScore(Object.values(daily));
    let streakResult = computeStreak(logs);
    let currentStreak = streakResult.currentStreak;
    let hasLoggedToday = (todayLogs.length > 0);
    let region = (appData?.region || "world");
    let benchmark = compareToBenchmark(totalKg, region);
    return { weekStart: startOfWeekISO(now), totalKg: totalKg, target: target, remaining: Math.max(0, (target - totalKg)), over: Math.max(0, (totalKg - target)), catTotals: catTotals, todayScore: todayScore, todayKg: todayKg, weeklyScore: weeklyScore, currentStreak: currentStreak, hasLoggedToday: hasLoggedToday, benchmark: benchmark, region: region, recentLogs: logs.slice().sort(sortByDateDesc).slice(0, 6) };
  };

  const summary = useMemo(() => computeSummary(ctx.state), [ctx]);

let items = [1];

const catEntries = Object.entries(CATEGORIES);
const goalColor = pickGoalColor(summary.over);
const goalProgress = Math.min((summary.totalKg / summary.target), 1);
const bmBg = pickBenchmarkBg(summary.benchmark.better);
const bmBorder = pickBenchmarkBorder(summary.benchmark.better);
const bmTextColor = pickBenchmarkTextColor(summary.benchmark.better);
const bmBannerStyle = [styles.benchmarkBanner, { backgroundColor: bmBg, borderColor: bmBorder }];
const bmBannerTextStyle = [styles.benchmarkBannerText, { color: bmTextColor }];
  return (
    <Screen>
      <FlatList
        data={items}
        keyExtractor={(item) => "home"}
        renderItem={({ item: item }) => (
          <View>
            <Card>
              <View style={styles.headerRow}>
                <View style={styles.scoreCircle} accessibilityLabel={`Today's score: ${summary.todayScore} out of 100`} accessibilityRole={"text"}>
                  <Text style={styles.scoreNum}>{summary.todayScore}</Text>
                  <Text style={styles.scoreLabel}>Today</Text>
                </View>
                <View style={{ flex: 1, marginLeft: 14 }}>
                  <Title>Nudge</Title>
                  <View style={{ flexDirection: "row", gap: 8, marginTop: 6, flexWrap: "wrap" }}>
                    <Chip kind={"brand"} label={`${summary.totalKg.toFixed(1)} kg this week`} />
                    <Chip label={`${summary.currentStreak} day streak`} />
                  </View>
                </View>
              </View>
              {((!summary.hasLoggedToday) && (summary.currentStreak > 0)) && (
                <View accessibilityRole={"alert"} style={styles.streakWarning}>
                  <Text style={styles.streakWarningText}>Log an activity today to keep your {summary.currentStreak}-day streak!</Text>
                </View>
              )}
              <View style={styles.catRow}>
                {catEntries.map((entry, __idx) => {
                  const key = entry[0];
                  const cat = entry[1];
                  const catMiniKgStyle = [styles.catMiniKg, { color: cat.color }];
                  return (
                    <View style={styles.catMini} accessibilityLabel={`${cat.label}: ${(summary.catTotals[key] || 0).toFixed(1)} kilograms`} key={__idx}>
                      <Text style={{ fontSize: 18 }}>{cat.icon}</Text>
                      <Text style={catMiniKgStyle}>{(summary.catTotals[key] || 0).toFixed(1)}</Text>
                      <Text style={styles.catMiniLabel}>kg</Text>
                    </View>
                  );
                })}
              </View>
            </Card>
            <View style={{ height: 12 }} />
            <Card>
              <View style={{ gap: 10 }}>
                <Button label={"+ Log Activity"} onPress={goLogActivity} accessibilityLabel={"Log a new activity"} />
                <View style={{ flexDirection: "row", gap: 10 }}>
                  <View style={{ flex: 1 }}>
                    <Button kind={"ghost"} label={"Dashboard"} onPress={goDashboard} accessibilityLabel={"View progress dashboard"} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Button kind={"ghost"} label={"Tips"} onPress={goTips} accessibilityLabel={"View weekly tips"} />
                  </View>
                </View>
                <View style={{ flexDirection: "row", gap: 10 }}>
                  <View style={{ flex: 1 }}>
                    <Button onPress={goBadges} accessibilityLabel={"View badges and streaks"} kind={"ghost"} label={"Badges"} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Button label={"Settings"} onPress={goSettings} accessibilityLabel={"Open settings"} kind={"ghost"} />
                  </View>
                </View>
                <Button kind={"ghost"} label={"Export Data"} onPress={goExport} accessibilityLabel={"Export data as CSV"} />
              </View>
            </Card>
            <View style={{ height: 12 }} />
            <Card>
              <Title style={{ fontSize: 16, textAlign: "center", marginBottom: 12 }}>Weekly Goal</Title>
              <View style={{ alignItems: "center" }}>
                <ProgressRing progress={goalProgress} size={140} strokeWidth={12} color={goalColor}>
                  <Text style={styles.ringMainText}>{summary.totalKg.toFixed(1)}</Text>
                  <Text style={styles.ringSubText}>/ {summary.target.toFixed(0)} kg</Text>
                </ProgressRing>
              </View>
              {(summary.over > 0) ? (
                <Muted style={{ marginTop: 10, fontSize: 12, textAlign: "center" }}>Over target by {summary.over.toFixed(1)} kg â check your tips for ideas!</Muted>
              ) : (
                <Muted style={{ marginTop: 10, fontSize: 12, textAlign: "center" }}>{summary.remaining.toFixed(1)} kg remaining this week</Muted>
              )}
            </Card>
            <View style={{ height: 12 }} />
            <Card>
              <Title style={{ fontSize: 16 }}>vs {summary.benchmark.benchmarkLabel}</Title>
              <View style={styles.benchmarkRow}>
                <View style={styles.benchmarkCol}>
                  <Text style={styles.benchmarkYou}>{summary.totalKg.toFixed(1)} kg</Text>
                  <Muted style={{ fontSize: 11 }}>You this week</Muted>
                </View>
                <View style={styles.benchmarkVs}>
                  <Text style={{ color: muted, fontWeight: "900", fontSize: 12 }}>vs</Text>
                </View>
                <View style={styles.benchmarkCol}>
                  <Text style={styles.benchmarkAvg}>{summary.benchmark.benchmarkKg} kg</Text>
                  <Muted style={{ fontSize: 11 }}>National avg</Muted>
                </View>
              </View>
              <View style={bmBannerStyle}>
                {summary.benchmark.better ? (
                  <Text style={bmBannerTextStyle}>You saved {summary.benchmark.savedKg.toFixed(1)} kg ({Math.abs(summary.benchmark.savedPct).toFixed(0)}% less) vs the {summary.benchmark.benchmarkLabel}</Text>
                ) : (
                  <Text style={bmBannerTextStyle}>{Math.abs(summary.benchmark.savedKg).toFixed(1)} kg above the {summary.benchmark.benchmarkLabel} â small changes add up!</Text>
                )}
              </View>
              <Muted style={{ marginTop: 6, fontSize: 10 }}>Source: {summary.benchmark.benchmarkSource}</Muted>
            </Card>
            <View style={{ height: 12 }} />
            <Card>
              <Title style={{ fontSize: 16 }}>Recent Activity</Title>
              <View style={{ height: 8 }} />
              {(summary.recentLogs.length === 0) ? (
                <Muted>No logs yet. Tap \"+ Log Activity\" to get started.</Muted>
              ) : (
                <>
                  {summary.recentLogs.map((item, __idx) => {
                    const logColor = pickLogColor((item.co2Kg || 0));
                    const logKgStyle = [styles.logKg, { color: logColor }];
                    const logPrefix = pickLogPrefix((item.co2Kg || 0));
                    const logVal = (item.co2Kg || 0).toFixed(2);
                    return (
                      <View style={styles.logRow} accessibilityLabel={`${item.label}, ${(item.co2Kg || 0).toFixed(2)} kg CO2`} key={__idx}>
                        <Text style={{ fontSize: 18, width: 28 }}>{(CATEGORIES[item.category || 'transport'])?.icon || ''}</Text>
                        <View style={{ flex: 1 }}>
                          <Text style={styles.logTitle}>{item.label}</Text>
                          <Muted style={{ fontSize: 11 }}>{new Date(item.dateISO).toLocaleDateString()}</Muted>
                        </View>
                        <Text style={logKgStyle}>{logPrefix}{logVal} kg</Text>
                      </View>
                    );
                  })}
                </>
              )}
            </Card>
            <View style={{ marginTop: 14 }}>
              <Muted style={{ textAlign: "center", fontSize: 11 }}>Educational estimates. Real emissions vary by region, vehicle, and habits.</Muted>
            </View>
            <View style={{ height: 20 }} />
          </View>
        )}
      />
    </Screen>
  );
}

const styles = StyleSheet.create({
  ringSubText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    fontWeight: "700",
  },
  benchmarkYou: {
    color: "#2dd4bf",
    fontSize: 22,
    fontWeight: "900",
  },
  benchmarkBanner: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
  },
  benchmarkVs: {
    paddingHorizontal: 12,
  },
  logKg: {
    fontWeight: "900",
    fontSize: 13,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  scoreLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 9,
    fontWeight: "700",
  },
  streakWarning: {
    backgroundColor: "rgba(245,158,11,0.12)",
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.35)",
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
  },
  streakWarningText: {
    color: "#f59e0b",
    fontWeight: "700",
    fontSize: 13,
    textAlign: "center",
  },
  benchmarkAvg: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 22,
    fontWeight: "900",
  },
  logRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
    gap: 8,
  },
  catMiniKg: {
    fontWeight: "900",
    fontSize: 16,
    marginTop: 2,
  },
  benchmarkRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  scoreCircle: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 3,
    borderColor: "#2dd4bf",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(45,212,191,0.08)",
  },
  benchmarkCol: {
    flex: 1,
    alignItems: "center",
  },
  benchmarkBannerText: {
    fontWeight: "700",
    fontSize: 13,
    textAlign: "center",
  },
  ringMainText: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 26,
    fontWeight: "900",
  },
  logTitle: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "700",
    fontSize: 14,
  },
  catMini: {
    alignItems: "center",
  },
  catRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.12)",
  },
  scoreNum: {
    color: "#2dd4bf",
    fontSize: 22,
    fontWeight: "900",
  },
  catMiniLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontWeight: "700",
  },
});
