// Generated by Quill (Expo mode)
import React, { useState, useContext, useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Button } from '../ui/components';
import { brand, textColor, muted, border } from '../ui/theme';
import { CATEGORIES, TRANSPORT_LABELS, CO2_FACTORS, getCategoryItems, computeCo2Kg } from '../lib/co2';
import { haversineKm } from '../lib/geo';
export let CAT_KEYS = Object.keys(CATEGORIES);
export default function LogActivityScreen({ navigation }) {
  const [category, setCategory] = useState("transport");
  const [selectedItem, setSelectedItem] = useState(null);
  const [quantity, setQuantity] = useState("1");
  const [notes, setNotes] = useState("");
  const [transport, setTransport] = useState("car");
  const [oneWayKm, setOneWayKm] = useState("");

  const ctx = useContext(AppContext);
  const suggestedKm = useMemo(() => computeSuggested(ctx.state), [ctx]);
  const items = useMemo(() => getCategoryItems(category, __propagate(ctx.state).region), [category, ctx]);
  const itemKeys = useMemo(() => Object.keys(items), [items]);
  const preview = useMemo(() => computePreview(), [category, transport, oneWayKm, selectedItem, quantity, items]);

  const computeSuggested = (appData) => {
    if (((!__propagate(appData).home) || (!__propagate(appData).school))) {
      return null;
    }
    return (haversineKm(appData.home, appData.school) * 1.25);
  };

  const computePreview = () => {
    if ((category === "transport")) {
      let km = Number(oneWayKm);
      if (((!Number.isFinite(km)) || (!(km > 0)))) {
        return null;
      }
      return computeCo2Kg({ transport: transport, oneWayKm: km });
    }
    if (((!selectedItem) || (!items[selectedItem]))) {
      return null;
    }
    let q = (Number(quantity) || 1);
    return (items[selectedItem].co2 * q);
  };

  const onSave = async () => {
    try {
      let log = null;
      if ((category === "transport")) {
        km = Number(oneWayKm);
        if (((!Number.isFinite(km)) || (!(km > 0)))) {
          throw new Error("Enter a valid distance");
        }
        let co2Kg = computeCo2Kg({ transport: transport, oneWayKm: km });
        log = { id: uuid(), dateISO: new Date().toISOString(), category: "transport", itemKey: transport, label: (TRANSPORT_LABELS[transport] || transport), co2Kg: co2Kg, quantity: 1, oneWayKm: km, transport: transport, transportLabel: (TRANSPORT_LABELS[transport] || transport), notes: (notes.trim() || null) };
      } else {
        if ((!selectedItem)) {
          throw new Error("Select an activity");
        }
        q = Math.max(1, Math.round((Number(quantity) || 1)));
        let item = items[selectedItem];
        log = { id: uuid(), dateISO: new Date().toISOString(), category: category, itemKey: selectedItem, label: item.label, co2Kg: (item.co2 * q), quantity: q, notes: (notes.trim() || null) };
      }
      let existingLogs = (__propagate(ctx.state).logs || []);
      let newLogs = Array.from(existingLogs);
      newLogs.unshift(log);
      let newState = Object.assign({}, ctx.state, { logs: newLogs });
      await ctx.setState(newState);
      navigation.navigate("Home");
    } catch (error) {
      Alert.alert("Log activity", (__propagate(error).message || "Could not save"));
    }
  };

  const selectCategory = (k) => {
    setCategory(k);
    setSelectedItem(null);
  };

  const selectTransport = (t) => {
    setTransport(t);
  };

  const selectItem = (k) => {
    setSelectedItem(k);
  };

  const onOneWayKmChange = (v) => {
    setOneWayKm(v);
  };

  const onQuantityChange = (v) => {
    setQuantity(v);
  };

  const onNotesChange = (v) => {
    setNotes(v);
  };

  const onUseSuggested = () => {
    setOneWayKm(suggestedKm.toFixed(1));
  };

  const onCancel = () => {
    navigation.navigate("Home");
  };

  const catPillStyle = (k) => {
    if ((category === k)) {
      return [catPill, { borderColor: CATEGORIES[k].color, backgroundColor: (CATEGORIES[k].color + "22") }];
    }
    return [catPill];
  };

  const catPillTextStyle = (k) => {
    if ((category === k)) {
      return [catPillText, { color: textColor }];
    }
    return [catPillText];
  };

  const itemPillStyle = (k) => {
    if ((selectedItem === k)) {
      return [itemPill, { borderColor: CATEGORIES[category].color, backgroundColor: (CATEGORIES[category].color + "22") }];
    }
    return [itemPill];
  };

  const itemTextStyle = (k) => {
    if ((selectedItem === k)) {
      return [pillText, { color: textColor }];
    }
    return [pillText];
  };

  const transportPillStyle = (t) => {
    if ((transport === t)) {
      return [pill, pillActive];
    }
    return [pill];
  };

  const transportPillTextStyle = (t) => {
    if ((transport === t)) {
      return [pillText, pillTextActive];
    }
    return [pillText];
  };

  const co2Prefix = (co2) => {
    if ((co2 > 0)) {
      return "+";
    }
    return "";
  };

  const previewColor = (val) => {
    if ((!(val < 0))) {
      return "#ef4444";
    }
    return "#22c55e";
  };

  const previewPrefix = (val) => {
    if ((!(val < 0))) {
      return "+";
    }
    return "";
  };

  return (
    <Screen>
      <ScrollView showsVerticalScrollIndicator={false}>
        <Card>
          <Title>Category</Title>
          <View style={styles.pillRow}>
            {CAT_KEYS.map((k, __idx) => (
              <>
                const catSty = catPillStyle(k);
                const catTxtSty = catPillTextStyle(k);
                const catHandler = selectCategory.bind(null, k);
                <Pressable onPress={() => catHandler()} style={styles.catSty}>
                  <Text style={styles.catTxtSty}>{CATEGORIES[k].icon} {CATEGORIES[k].label}</Text>
                </Pressable>
              </>
            ))}
          </View>
        </Card>
        <View style={{ height: 12 }} />
        <Card>
          <Title style={{ fontSize: 18 }}>{CATEGORIES[category].icon} {CATEGORIES[category].label} Activity</Title>
          {(category === "transport") ? (
            <>
              <Muted style={{ marginTop: 6 }}>Select transport mode and enter one-way distance.</Muted>
              <View style={styles.pillRow}>
                {Object.keys(TRANSPORT_LABELS).map((t, __idx) => (
                  <>
                    const tSty = transportPillStyle(t);
                    const tTxtSty = transportPillTextStyle(t);
                    const tHandler = selectTransport.bind(null, t);
                    <Pressable onPress={() => tHandler()} style={styles.tSty}>
                      <Text style={styles.tTxtSty}>{TRANSPORT_LABELS[t]}</Text>
                    </Pressable>
                  </>
                ))}
              </View>
              <Text style={styles.label}>One-way distance (km)</Text>
              <TextInput onChangeText={onOneWayKmChange} keyboardType={"numeric"} placeholder={"e.g., 7.5"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} value={oneWayKm} />
              {suggestedKm && (
                <Button kind={"ghost"} label={`Use suggested: ~${suggestedKm.toFixed(1)} km`} onPress={() => onUseSuggested()} />
              )}
            </>
          ) : (
            <Muted style={{ marginTop: 6 }}>Tap an activity to select it.</Muted>
            <View style={styles.pillRow}>
              {itemKeys.map((k, __idx) => (
                <>
                  const item = items[k];
                  const iSty = itemPillStyle(k);
                  const iTxtSty = itemTextStyle(k);
                  const iHandler = selectItem.bind(null, k);
                  <Pressable onPress={() => iHandler()} style={styles.iSty}>
                    <Text style={styles.iTxtSty}>{item.icon} {item.label}</Text>
                    <Text style={styles.co2Badge}>{co2Prefix(item.co2)}{item.co2} kg</Text>
                  </Pressable>
                </>
              ))}
            </View>
            {selectedItem && (
              <View style={{ marginTop: 8 }}>
                <Text style={styles.label}>Quantity / times</Text>
                <TextInput keyboardType={"numeric"} placeholder={"1"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} value={quantity} onChangeText={onQuantityChange} />
              </View>
            )}
          )}
        </Card>
        <View style={{ height: 12 }} />
        <Card>
          {(preview != null) && (
            <>
              const pvColor = previewColor(preview);
              const pvSty = [previewValue, { color: pvColor }];
              <View style={styles.previewBox}>
                <Text style={styles.previewLabel}>CO2e impact</Text>
                <Text style={styles.pvSty}>{previewPrefix(preview)}{preview.toFixed(2)} kg CO2e</Text>
              </View>
            </>
          )}
          <Text style={styles.label}>Notes (optional)</Text>
          const notesSty = [inputStyle, { minHeight: 60, textAlignVertical: "top" }];
          <TextInput value={notes} onChangeText={onNotesChange} style={styles.notesSty} multiline={true} placeholder={"e.g., carpooled with 2 friends"} placeholderTextColor={"rgba(255,255,255,0.45)"} />
          <View style={{ marginTop: 14, gap: 10 }}>
            <Button label={"Save Activity"} onPress={() => onSave()} />
            <Button kind={"ghost"} label={"Cancel"} onPress={() => onCancel()} />
          </View>
        </Card>
        <View style={{ height: 30 }} />
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  catPillText: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    fontSize: 13,
  },
  previewValue: {
    fontSize: 28,
    fontWeight: "900",
    marginTop: 4,
  },
  pillRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
  },
  catPill: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  pillTextActive: {
    color: "rgba(255,255,255,0.92)",
  },
  co2Badge: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 10,
    fontWeight: "700",
  },
  label: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    marginBottom: 6,
    marginTop: 10,
  },
  inputStyle: {
    color: "rgba(255,255,255,0.92)",
    borderColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  pill: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  pillText: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    fontSize: 12,
  },
  previewBox: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    alignItems: "center",
  },
  previewLabel: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    fontWeight: "700",
  },
  pillActive: {
    borderColor: "rgba(45,212,191,0.6)",
    backgroundColor: "rgba(45,212,191,0.15)",
  },
  itemPill: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.02)",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
});
