// Generated by Quill (Expo mode)
import React, { useState, useContext, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Button } from '../ui/components';
import { brand, textColor } from '../ui/theme';
import { REGIONS } from '../lib/regions';
export let STEPS = ["welcome", "school", "region", "target"];
export default function OnboardingScreen() {
  const ctx = useContext(AppContext);
  const [step, setStep] = useState(0);
  const [schoolName, setSchoolName] = useState("");
  const [schoolLat, setSchoolLat] = useState("");
  const [schoolLon, setSchoolLon] = useState("");
  const [region, setRegion] = useState("world");
  const [target, setTarget] = useState("10");

  const current = useMemo(() => STEPS[step], [step]);
  const justify = useMemo(() => justifyForStep(), [step]);

  const goStep1 = () => {
    setStep(1);
  };

  const goStep2 = () => {
    setStep(2);
  };

  const goStep3 = () => {
    setStep(3);
  };

  const onSchoolNameChange = (v) => {
    setSchoolName(v);
  };

  const onSchoolLatChange = (v) => {
    setSchoolLat(v);
  };

  const onSchoolLonChange = (v) => {
    setSchoolLon(v);
  };

  const onTargetChange = (v) => {
    setTarget(v);
  };

  const selectRegion = (k) => {
    setRegion(k);
  };

  const buildSchool = () => {
    if (schoolName.trim()) {
      return { name: schoolName.trim(), latitude: Number(schoolLat), longitude: Number(schoolLon) };
    }
    return null;
  };

  const regionButtonKind = (key) => {
    if ((region === key)) {
      return "primary";
    }
    return "ghost";
  };

  const dotStyleForIndex = (i) => {
    if ((i === step)) {
      return [dot, dotActive];
    }
    return [dot];
  };

  const justifyForStep = () => {
    if ((!(step > 1))) {
      return "center";
    }
    return null;
  };

  const onFinish = async () => {
    try {
      let lat = Number(schoolLat);
      let lon = Number(schoolLon);
      let t = Number(target);
      if ((schoolName.trim() && ((!Number.isFinite(lat)) || (!Number.isFinite(lon))))) {
        throw new Error("Please enter valid coordinates for your school.");
      }
      let latOutOfRange = ((lat < (-90)) || (lat > 90));
      let lonOutOfRange = ((lon < (-180)) || (lon > 180));
      if ((schoolName.trim() && (latOutOfRange || lonOutOfRange))) {
        throw new Error("Coordinates out of range.");
      }
      if (((!Number.isFinite(t)) || (!(t > 0)))) {
        throw new Error("Target must be a positive number.");
      }
      let school = buildSchool();
      let newState = Object.assign({}, ctx.state, { school: school, region: region, targetKgPerWeek: t, onboarded: true });
      await ctx.setState(newState);
    } catch (error) {
      Alert.alert("Setup", (__propagate(error).message || "Could not save"));
    }
  };

  return (
    <Screen>
      <ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps={"handled"} contentContainerStyle={styles.scrollContent}>
        {(current === "welcome") && (
          <Card>
            <Text style={styles.emoji}>🌍</Text>
            <Title style={styles.welcomeTitle}>Welcome to Nudge</Title>
            <Muted style={styles.welcomeBody}>Track your carbon footprint, earn badges, and get personalised tips to reduce your environmental impact.</Muted>
            <View style={styles.spacerLg}>
              <Button label={"Get Started"} onPress={() => goStep1()} />
            </View>
          </Card>
        )}
        {(current === "school") && (
          <Card>
            <Title>Your School</Title>
            <Muted style={styles.spacerSm}>Enter your school details to estimate commute distance. You can skip this and set it later in Settings.</Muted>
            <Text style={styles.label}>School name</Text>
            <TextInput value={schoolName} onChangeText={onSchoolNameChange} placeholder={"e.g. Dubai College"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"School name"} />
            <View style={styles.coordRow}>
              <View style={styles.flexOne}>
                <Text style={styles.label}>Latitude</Text>
                <TextInput value={schoolLat} onChangeText={onSchoolLatChange} placeholder={"25.2048"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"Latitude"} />
              </View>
              <View style={styles.flexOne}>
                <Text style={styles.label}>Longitude</Text>
                <TextInput value={schoolLon} onChangeText={onSchoolLonChange} placeholder={"55.2708"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"Longitude"} />
              </View>
            </View>
            <View style={styles.buttonGroup}>
              <Button onPress={() => goStep2()} label={"Next"} />
              <Button kind={"ghost"} label={"Skip for now"} onPress={() => goStep2()} />
            </View>
          </Card>
        )}
        {(current === "region") && (
          <Card>
            <Title>Your Region</Title>
            <Muted style={styles.spacerSm}>Electricity grid carbon intensity varies by region. Pick yours for more accurate energy estimates.</Muted>
            <View style={styles.regionGrid}>
              {Object.entries(REGIONS).map((entry, __idx) => (
                <>
                  const rKey = entry[0];
                  const rVal = entry[1];
                  const bk = regionButtonKind(rKey);
                  const rl = rVal.label;
                  const handler = selectRegion.bind(null, rKey);
                  <Button kind={bk} label={rl} onPress={() => handler()} />
                </>
              ))}
            </View>
            <View style={styles.buttonGroup}>
              <Button onPress={() => goStep3()} label={"Next"} />
            </View>
          </Card>
        )}
        {(current === "target") && (
          <Card>
            <Title>Weekly Target</Title>
            <Muted style={styles.spacerSm}>Set a weekly CO2 budget in kg. The average person produces about 22 kg/day. A stretching but achievable student target is 10 kg/week.</Muted>
            <Text style={styles.label}>Target (kg CO2 / week)</Text>
            <TextInput value={target} onChangeText={onTargetChange} placeholder={"10"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"Target (kg CO2 / week)"} />
            <View style={styles.buttonGroup}>
              <Button label={"Start Tracking"} onPress={() => onFinish()} />
            </View>
          </Card>
        )}
        <View style={styles.dots}>
          {STEPS.map((s, __idx) => (
            <>
              const idx = STEPS.indexOf(s);
              const ds = dotStyleForIndex(idx);
              const al = `Step ${idx + 1} of ${STEPS.length}`;
              <View style={ds} accessibilityLabel={al} />
            </>
          ))}
        </View>
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  spacerLg: {
    marginTop: 24,
  },
  inputStyle: {
    color: "rgba(255,255,255,0.92)",
    borderColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  dots: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginTop: 24,
  },
  coordRow: {
    flexDirection: "row",
    gap: 10,
  },
  emoji: {
    fontSize: 56,
    textAlign: "center",
    marginBottom: 12,
  },
  label: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    marginBottom: 6,
    marginTop: 10,
  },
  buttonGroup: {
    marginTop: 14,
    gap: 10,
  },
  welcomeBody: {
    textAlign: "center",
    marginTop: 10,
    lineHeight: 20,
  },
  spacerSm: {
    marginTop: 6,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  welcomeTitle: {
    textAlign: "center",
    fontSize: 28,
  },
  flexOne: {
    flex: 1,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.2)",
  },
  dotActive: {
    backgroundColor: "#2dd4bf",
    width: 24,
  },
  regionGrid: {
    gap: 8,
    marginTop: 12,
  },
});
