// Generated by Quill (Expo mode)
import React, { useState, useEffect, useContext, useMemo } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted, Button, Chip } from '../ui/components';
import { textColor, muted, border, brand } from '../ui/theme';
import { REGIONS } from '../lib/regions';
import { scheduleDailyReminder, cancelAllReminders } from '../lib/notifications';
export let REGION_ENTRIES = Object.entries(REGIONS);
export function RegionPill({ entry, region, onSelect }) {
  const key = useMemo(() => deriveKey(entry), [entry]);
  const label = useMemo(() => deriveLabel(entry), [entry]);
  const isActive = useMemo(() => deriveActive(region, entry), [region, entry]);

  const deriveKey = (e) => {
    return e[0];
  };

  const deriveLabel = (e) => {
    return e[1].label;
  };

  const deriveActive = (reg, e) => {
    return (reg === e[0]);
  };

  const handlePress = () => {
    onSelect(entry[0]);
  };

  return (
    <>
      {isActive ? (
        <Pressable style={styles.rpActive} accessibilityLabel={`Region: ${label}`} accessibilityRole={"button"} onPress={() => handlePress()}>
          <Text style={styles.rtActive}>{label}</Text>
        </Pressable>
      ) : (
        <Pressable accessibilityLabel={`Region: ${label}`} accessibilityRole={"button"} onPress={() => handlePress()} style={styles.rpBase}>
          <Text style={styles.rtBase}>{label}</Text>
        </Pressable>
      )}
    </>
  );
}

export default function SettingsScreen({ navigation }) {
  const [schoolName, setSchoolName] = useState((__propagate(__propagate(ctx.state).school).name || ""));
  const [schoolLat, setSchoolLat] = useState("");
  const [schoolLon, setSchoolLon] = useState("");
  const [target, setTarget] = useState(String((__propagate(ctx.state).targetKgPerWeek || 10)));
  const [region, setRegion] = useState((__propagate(ctx.state).region || "world"));
  const [reminderOn, setReminderOn] = useState(true);

  const ctx = useContext(AppContext);
  const chipLabel = useMemo(() => deriveChipLabel(ctx), [ctx]);
  const chipKind = useMemo(() => deriveChipKind(ctx), [ctx]);
  const remLabel = useMemo(() => deriveRemLabel(reminderOn), [reminderOn]);
  const remAccessLabel = useMemo(() => deriveRemAccessLabel(reminderOn), [reminderOn]);

  useEffect(() => {
    if (__propagate(ctx.state).school) {
      setSchoolLat(String(ctx.state.school.latitude));
      setSchoolLon(String(ctx.state.school.longitude));
    }
  }, []);

  const schoolObj = (lat, lon) => {
    return { name: schoolName.trim(), latitude: lat, longitude: lon };
  };

  const onSave = async () => {
    try {
      let lat = Number(schoolLat);
      let lon = Number(schoolLon);
      let t = Number(target);
      let hasSchool = ((schoolName.trim() && schoolLat) && schoolLon);
      if (hasSchool) {
        if (((!Number.isFinite(lat)) || (!Number.isFinite(lon)))) {
          throw new Error("School coordinates must be numbers");
        }
        if (((lat < (-90)) || (lat > 90))) {
          throw new Error("Latitude must be between -90 and 90");
        }
        if (((lon < (-180)) || (lon > 180))) {
          throw new Error("Longitude must be between -180 and 180");
        }
      }
      if (((!Number.isFinite(t)) || (!(t > 0)))) {
        throw new Error("Target must be a positive number");
      }
      let schoolValue = __propagate(ctx.state).school;
      if (hasSchool) {
        schoolValue = schoolObj(lat, lon);
      }
      let newState = Object.assign({}, ctx.state, { school: schoolValue, targetKgPerWeek: t, region: region });
      await ctx.setState(newState);
      Alert.alert("Saved", "Settings updated.");
      navigation.navigate("Home");
    } catch (error) {
      Alert.alert("Settings", (__propagate(error).message || "Could not save"));
    }
  };

  const toggleReminder = async () => {
    if (reminderOn) {
      await cancelAllReminders();
      setReminderOn(false);
      Alert.alert("Reminders", "Daily reminders turned off.");
    } else {
      let id = await scheduleDailyReminder(20, 0);
      setReminderOn(true);
      if (id) {
        Alert.alert("Reminders", "You will be reminded at 8pm daily to log your activities.");
      } else {
        Alert.alert("Reminders", "Could not enable reminders. Please check notification permissions.");
      }
    }
  };

  const deriveChipLabel = (c) => {
    if (__propagate(c.state).home) {
      return ("Home set: " + (c.state.home.label || ((c.state.home.latitude.toFixed(4) + ", ") + c.state.home.longitude.toFixed(4))));
    }
    return "Home not set yet";
  };

  const deriveChipKind = (c) => {
    if (__propagate(c.state).home) {
      return "brand";
    }
    return null;
  };

  const deriveRemLabel = (isOn) => {
    if (isOn) {
      return "Turn Off Daily Reminder";
    }
    return "Turn On Daily Reminder (8pm)";
  };

  const deriveRemAccessLabel = (isOn) => {
    if (isOn) {
      return "Disable daily notification reminder";
    }
    return "Enable daily notification reminder at 8pm";
  };

  const onSchoolNameChange = (v) => {
    setSchoolName(v);
  };

  const onSchoolLatChange = (v) => {
    setSchoolLat(v);
  };

  const onSchoolLonChange = (v) => {
    setSchoolLon(v);
  };

  const onTargetChange = (v) => {
    setTarget(v);
  };

  const goPickLocation = () => {
    navigation.navigate("PickLocation");
  };

  const selectRegion = (k) => {
    setRegion(k);
  };

  return (
    <Screen>
      <View style={styles.flex1}>
        <Card>
          <Title>School</Title>
          <Muted style={styles.marginTop6}>Set your school location to estimate commute distance.</Muted>
          <Text style={styles.label}>School name</Text>
          <TextInput onChangeText={onSchoolNameChange} placeholder={"e.g. Dubai College"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"School name"} value={schoolName} />
          <View style={styles.coordRow}>
            <View style={styles.flex1}>
              <Text style={styles.label}>Latitude</Text>
              <TextInput placeholder={"25.2048"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"Latitude"} value={schoolLat} onChangeText={onSchoolLatChange} />
            </View>
            <View style={styles.flex1}>
              <Text style={styles.label}>Longitude</Text>
              <TextInput value={schoolLon} onChangeText={onSchoolLonChange} placeholder={"55.2708"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} style={styles.inputStyle} accessibilityLabel={"Longitude"} />
            </View>
          </View>
          <Button kind={"ghost"} label={"Pick my home location (map)"} onPress={() => goPickLocation()} accessibilityLabel={"Pick home location on map"} />
          <View style={styles.marginTop10}>
            <Chip kind={chipKind} label={chipLabel} />
          </View>
        </Card>
        <View style={styles.spacer12} />
        <Card>
          <Title>Region</Title>
          <Muted style={styles.marginTop6}>Electricity grid carbon intensity varies by region. This adjusts your energy emission estimates.</Muted>
          <View style={styles.regionGrid}>
            {REGION_ENTRIES.map((entry, __idx) => (
              <RegionPill entry={entry} region={region} onSelect={() => selectRegion()} />
            ))}
          </View>
        </Card>
        <View style={styles.spacer12} />
        <Card>
          <Title>Targets & Reminders</Title>
          <Muted style={styles.marginTop6}>Weekly CO2 goal (kg).</Muted>
          <Text style={styles.label}>Target kg CO2 / week</Text>
          <TextInput style={styles.inputStyle} accessibilityLabel={"Target kg CO2 / week"} value={target} onChangeText={onTargetChange} placeholder={"10"} keyboardType={"numeric"} placeholderTextColor={"rgba(255,255,255,0.45)"} />
          <View style={styles.marginTop4}>
            <Button kind={"ghost"} label={remLabel} onPress={() => toggleReminder()} accessibilityLabel={remAccessLabel} />
          </View>
          <View style={styles.marginTop14}>
            <Button label={"Save Settings"} onPress={() => onSave()} accessibilityLabel={"Save all settings"} />
          </View>
        </Card>
        <View style={styles.marginTop12}>
          <Muted>Tip: if you don't want maps or location permissions, you can still log commutes by entering distance manually.</Muted>
        </View>
      </View>
    </Screen>
  );
}

const styles = StyleSheet.create({
  flex1: {
    flex: 1,
  },
  coordRow: {
    flexDirection: "row",
    gap: 10,
  },
  marginTop4: {
    marginTop: 4,
  },
  spacer12: {
    height: 12,
  },
  regionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  rpActive: {
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderColor: "rgba(45,212,191,0.6)",
    backgroundColor: "rgba(45,212,191,0.15)",
  },
  rtBase: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "700",
    fontSize: 12,
  },
  inputStyle: {
    color: "rgba(255,255,255,0.92)",
    borderColor: "rgba(255,255,255,0.12)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    marginBottom: 10,
  },
  marginTop6: {
    marginTop: 6,
  },
  rtActive: {
    color: textColor,
    fontWeight: "700",
    fontSize: 12,
  },
  rpBase: {
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  label: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "900",
    marginBottom: 6,
  },
  marginTop10: {
    marginTop: 10,
  },
  marginTop14: {
    marginTop: 14,
  },
  marginTop12: {
    marginTop: 12,
  },
});
