// Generated by Quill (Expo mode)
import React, { useContext, useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { AppContext } from '../state/context';
import { Screen, Card, Title, Muted } from '../ui/components';
import { textColor, muted, border } from '../ui/theme';
import { CATEGORIES } from '../lib/co2';
import { getPersonalisedTips, getWorstCategory } from '../lib/tips';
import { weekKeyISO } from '../utils/time';
export default function TipsScreen() {
  const ctx = useContext(AppContext);

  const lookupWorstInfo = (r) => {
    return (CATEGORIES[r.worstCat] || CATEGORIES.transport);
  };

  const computeTips = (appData) => {
    let logs = (appData?.logs || []);
    let now = new Date();
    let wk = weekKeyISO(now);
    let weekLogs = logs.filter((l) => (weekKeyISO(new Date(l.dateISO)) === wk));
    let totals = { transport: 0, diet: 0, energy: 0, waste: 0 };
    for (const l of weekLogs) {
      let cat = (l.category || "transport");
      totals[cat] = ((totals[cat] || 0) + Math.max(0, (l.co2Kg || 0)));
    }
    let worst = getWorstCategory(totals);
    let personalised = getPersonalisedTips(totals, 5);
    let enriched = personalised.map((t) => {
      let ci = (CATEGORIES[t.category] || CATEGORIES.transport);
      return { tip: t.tip, category: t.category, catIcon: ci.icon, catLabel: ci.label, catColor: ci.color };
    });
    return { tips: enriched, worstCat: worst, catTotals: totals };
  };

  const summaryValueStyle = (key) => {
    if ((key === result.worstCat)) {
      return { color: "#ef4444", fontWeight: "900", fontSize: 14 };
    } else {
      return { color: "rgba(255,255,255,0.68)", fontWeight: "700", fontSize: 14 };
    }
  };

  const result = useMemo(() => computeTips(ctx.state), [ctx]);
  const worstInfo = useMemo(() => lookupWorstInfo(result), [result]);

  return (
    <Screen>
      <ScrollView showsVerticalScrollIndicator={false}>
        <Card>
          <Title>Your Weekly Tips</Title>
          <Muted style={styles.mutedMarginTop6}>Personalised suggestions based on your activity this week.</Muted>
          <View style={styles.worstBox}>
            <Text style={styles.worstIcon}>{worstInfo.icon}</Text>
            <View style={styles.flex1}>
              <Text style={styles.worstTitle}>Focus area: {worstInfo.label}</Text>
              <Text style={styles.worstSub}>{result.catTotals[result.worstCat].toFixed(1)} kg CO2e this week â your highest category</Text>
            </View>
          </View>
        </Card>
        <View style={styles.spacer12} />
        {result.tips.map((t, __idx) => (
          <View key={__idx}>
            <Card style={{ borderLeftWidth: 3, borderLeftColor: t.catColor }}>
              <View style={styles.tipHeader}>
                <Text style={{ fontWeight: "900", fontSize: 12, textTransform: "uppercase", letterSpacing: 0.5, color: t.catColor }}>{t.catIcon} {t.catLabel}</Text>
              </View>
              <Text style={styles.tipText}>{t.tip}</Text>
            </Card>
            <View style={styles.spacer10} />
          </View>
        ))}
        {(result.tips.length === 0) && (
          <Card>
            <Muted>Log some activities this week to get personalised tips!</Muted>
          </Card>
        )}
        <View style={styles.spacer12} />
        <Card>
          <Title style={styles.titleSmall}>Category Summary</Title>
          <View style={styles.marginTop10}>
            {Object.entries(CATEGORIES).map((entry, __idx) => {
              const key = entry[0];
              const cat = entry[1];
              const svs = summaryValueStyle(key);
              return (
                <View key={__idx} style={styles.summaryRow}>
                  <Text style={styles.summaryLabel}>{cat.icon} {cat.label}</Text>
                  <Text style={{ color: svs.color, fontWeight: svs.fontWeight, fontSize: 14 }}>{(result.catTotals[key] || 0).toFixed(2)} kg</Text>
                </View>
              );
            })}
          </View>
        </Card>
        <View style={styles.spacer30} />
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  worstIcon: {
    fontSize: 32,
  },
  summaryLabel: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "700",
    fontSize: 14,
  },
  flex1: {
    flex: 1,
  },
  mutedMarginTop6: {
    marginTop: 6,
  },
  spacer12: {
    height: 12,
  },
  spacer10: {
    height: 10,
  },
  summaryHighlight: {
    color: "#ef4444",
    fontWeight: "900",
  },
  titleSmall: {
    fontSize: 16,
  },
  worstBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(239,68,68,0.08)",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.3)",
    borderRadius: 12,
    padding: 14,
    marginTop: 14,
    gap: 12,
  },
  worstSub: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 12,
    marginTop: 2,
  },
  tipCard: {
    borderLeftWidth: 3,
  },
  summaryValue: {
    color: "rgba(255,255,255,0.68)",
    fontWeight: "700",
    fontSize: 14,
  },
  worstTitle: {
    color: "rgba(255,255,255,0.92)",
    fontWeight: "900",
    fontSize: 16,
  },
  tipCat: {
    fontWeight: "900",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tipHeader: {
    marginBottom: 6,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.12)",
  },
  tipText: {
    color: "rgba(255,255,255,0.92)",
    fontSize: 14,
    lineHeight: 20,
  },
  spacer30: {
    height: 30,
  },
  marginTop10: {
    marginTop: 10,
  },
});
